#!/bin/sh

#GET BRANCH NAME
NAME=$(git branch | grep '*' | sed 's/* //')

#GET TIMESTAMP
TIMESTAMP=$(date +"%D %T")

#GET BRANCH DESCRIPTION
DESCRIPTION=$(git config branch."$NAME".description)

echo $1

echo "$TIMESTAMP — $NAME"': '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION" ]
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi